# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://devopsfti1.postgres.database.azure.com/postgres
    username: emine
    password: Informatika2024
  # JPA properties
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Server configuration
server:
  port: 9090
# Security configuration
security:
  user:
    name: user
password: user